### ISSUE TITLE
无法运行FedMDFG与FedLF

### ISSUE THREAD

**Issue by Paridis7** [zibinpan/FedLF#1]
你好，按照您所给出的运行指令，我将algorithm参数改为FedMDFG与FedLF均无法运行，其他方法都是可以运行的。报错如下：
AttributeError: module 'gfedplat' has no attribute 'FedMDFG'
AttributeError: module 'gfedplat' has no attribute 'FedLF'

使用的指令如下：
python run.py --seed 1 --device 0 --module CNN --algorithm FedMDFG--dataloader DataLoader_cifar10_dir --N 100 --Diralpha 0.1 --B 50 --C 0.1 --R 3000 --E 1 --lr 0.1 --decay 0.999

python run.py --seed 1 --device 0 --module CNN --algorithm FedLF --dataloader DataLoader_cifar10_dir --N 100 --Diralpha 0.1 --B 50 --C 0.1 --R 3000 --E 1 --lr 0.1 --decay 0.999

**Comment by zibinpan** [comment]
感谢发现问题，是之前的init文件没有导入所致。已修改。
